name: ToastyWarns
main: me.CyberCube_.TW.Main
version: 1.0
commands:
  warn:
    default: op
    description: Warn a player
    usage: /<command>
    permission: toastywarn.warn
    permission-message: You don't have the permission to use this command!
    aliases: [wr]
  warning:
    default: op
    description: See/Remove players warn
    usage: /<command> [remove/see] [Player]
    permission: toastywarn.warning
    permission-message: You don't have the permission to use this command!
    aliases: [wrg]